### PR TITLE
fix : floor의 rigidbody

### LINKED ISSUE #86: PacketStream 투사체 비활성화 버그
패킷 스트림 투사체가 나오자마자 바로 비활성화가 되는 버그가 있습니다.

floor의 rigidbody를 없애면 다시 정상작동하는걸 확인했습니다.

### PR DESCRIPTION
**Pull request by tpwls6630**
# PR Fix issue#86
Link or reference any related issues or tickets.

close #86
### Changes Included
- [ ] floor의 rigidbody 삭제
- [x] P_Beam이 땅에 부딫힐 때 사라지는 로직 변경

### Notes for Reviewer

---
## Reviewer Checklist
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.
---

### CODE REVIEW

**Comment by Nyso97** [comment]
Rigidbody 삭제가 안되어있습니다

**Review by Nyso97 — CHANGES_REQUESTED** [review]
rigidbody 삭제 안되어있습니다.

**Comment by tpwls6630** [comment]
근데 뭔가 유니티 씬 충돌 날 거 같네요

**Review by Nyso97 — APPROVED** [review]

**Comment by Nyso97** [comment]
알림 왔던 것 같습니다 제대로 못봤네요;;

**Pull request merged**
